const countriesData = [ 
  { country: 'Denmark', continent: 'Europe', happinessScore: 7 },
{ country: 'Switzerland',
  continent: 'Europe',
  happinessScore: 7 },
{ country: 'Iceland', continent: 'Europe', happinessScore: 7 },
{ country: 'Norway', continent: 'Europe', happinessScore: 7 },
{ country: 'Finland', continent: 'Europe', happinessScore: 7 },
{ country: 'Canada',
  continent: 'North America',
  happinessScore: 7 },
{ country: 'Netherlands',
  continent: 'Europe',
  happinessScore: 7 },
{ country: 'New Zealand',
  continent: 'Australia',
  happinessScore: 7 },
{ country: 'Australia',
  continent: 'Australia',
  happinessScore: 7 },
{ country: 'Sweden', continent: 'Europe', happinessScore: 7 },
{ country: 'Israel', continent: 'Asia', happinessScore: 7 },
{ country: 'Austria', continent: 'Europe', happinessScore: 7 },
{ country: 'United States',
  continent: 'North America',
  happinessScore: 7 },
{ country: 'Costa Rica',
  continent: 'South America',
  happinessScore: 7 },
{ country: 'Puerto Rico',
  continent: 'South America',
  happinessScore: 7 },
{ country: 'Germany', continent: 'Europe', happinessScore: 6 },
{ country: 'Brazil',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Belgium', continent: 'Europe', happinessScore: 6 },
{ country: 'Ireland', continent: 'Europe', happinessScore: 6 },
{ country: 'Luxembourg', continent: 'Europe', happinessScore: 6 },
{ country: 'Mexico',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Singapore', continent: 'Asia', happinessScore: 6 },
{ country: 'United Kingdom',
  continent: 'Europe',
  happinessScore: 6 },
{ country: 'Chile',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Panama',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Argentina',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Czech Republic',
  continent: 'Europe',
  happinessScore: 6 },
{ country: 'United Arab Emirates',
  continent: 'Asia',
  happinessScore: 6 },
{ country: 'Uruguay',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Malta', continent: 'Europe', happinessScore: 6 },
{ country: 'Colombia',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'France', continent: 'Europe', happinessScore: 6 },
{ country: 'Thailand', continent: 'Asia', happinessScore: 6 },
{ country: 'Saudi Arabia', continent: 'Asia', happinessScore: 6 },
{ country: 'Taiwan', continent: 'Asia', happinessScore: 6 },
{ country: 'Qatar', continent: 'Asia', happinessScore: 6 },
{ country: 'Spain', continent: 'Europe', happinessScore: 6 },
{ country: 'Algeria', continent: 'Africa', happinessScore: 6 },
{ country: 'Guatemala',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Suriname',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Kuwait', continent: 'Asia', happinessScore: 6 },
{ country: 'Bahrain', continent: 'Asia', happinessScore: 6 },
{ country: 'Trinidad and Tobago',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Venezuela',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Slovakia', continent: 'Europe', happinessScore: 6 },
{ country: 'El Salvador',
  continent: 'South America',
  happinessScore: 6 },
{ country: 'Malaysia', continent: 'Asia', happinessScore: 6 },
{ country: 'Nicaragua',
  continent: 'South America',
  happinessScore: 5 },
{ country: 'Uzbekistan', continent: 'Europe', happinessScore: 5 },
{ country: 'Italy', continent: 'Europe', happinessScore: 5 },
{ country: 'Ecuador',
  continent: 'South America',
  happinessScore: 5 },
{ country: 'Belize', continent: 'South America', happinessScore: 5 },
{ country: 'Japan', continent: 'Asia', happinessScore: 5 },
{ country: 'Kazakhstan', continent: 'Europe', happinessScore: 5 },
{ country: 'Moldova', continent: 'Europe', happinessScore: 5 },
{ country: 'Russia', continent: 'Europe', happinessScore: 5 },
{ country: 'Poland', continent: 'Europe', happinessScore: 5 },
{ country: 'South Korea', continent: 'Asia', happinessScore: 5 },
{ country: 'Bolivia',
  continent: 'South America',
  happinessScore: 5 },
{ country: 'Lithuania', continent: 'Europe', happinessScore: 5 } 
]

module.exports = countriesData;